version: '3'
    
services:
    backend:
        container_name: backend
        build: ./backend
        restart: unless-stopped
        ports:
            - 5000:5000
        command: npm run dev # Used for running backend with nodemon
        environment:
            MONGO_USER: $MONGO_USER
            MONGO_PASS: $MONGO_PASS
            SENDGRID_API_KEY: $SENDGRID_API_KEY
        volumes:
            - ./backend:/app
        depends_on: 
            - mongo

    client:
        container_name:  client
        build: ./client
        restart: unless-stopped
        ports:
            - 3000:3000
        stdin_open: true # React container fails without this
        volumes:
            - ./client:/app
        depends_on: 
            - backend

    # Connection String:
    # mongodb://root:example@localhost:27012
    mongo:
        container_name: mongo
        image: mongo
        restart: unless-stopped
        ports: 
            - 27012:27017 # Used for connection with MongoDb Compass
        environment:
            MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
            MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS
        volumes: 
            - mongo:/data/db
    
    mongo-express:
        container_name: mongo-express
        image: mongo-express
        restart: unless-stopped
        ports:
            - 8081:8081
        depends_on: 
            - mongo
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USER
            ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASS

volumes:
    mongo: