version: '3'
    
services:
    backend:
        container_name: backend
        build: ./backend
        ports:
            - 5000:5000
        command: npm run dev # Used for running backend with nodemon
        environment:
            - TESTVAR=${TESTVAR}
        volumes:
            - ./backend:/app
        depends_on: 
            - mongo

    client:
        container_name:  client
        build: ./client
        ports:
            - 3000:3000
        stdin_open: true # React container fails without this
        volumes:
            - ./client:/app
        depends_on: 
            - backend

    # Connection String:
    # mongodb://root:example@localhost:27012
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports: 
            - 27012:27017 # Used for connection with MongoDb Compass
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    
    mongo-express:
        container_name: mongo-express
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        depends_on: 
            - mongo
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example