version: '3'
    
services:
    backend:
        build: ./backend
        ports:
            - 5000:5000
        command: npm run dev

    client:
        build: ./client
        ports:
            - 3000:3000
        stdin_open: true